"""Pydantic schemas for cyclone tracks, vulnerability features, and anticipatory advisories."""

from enum import Enum
from typing import List, Optional
from pydantic import BaseModel, Field


class TrackCategory(str, Enum):
    """IMD tropical cyclone intensity classification."""

    LOW_PRESSURE = "Low Pressure Area"
    DEPRESSION = "Depression"
    DEEP_DEPRESSION = "Deep Depression"
    CYCLONIC_STORM = "Cyclonic Storm"
    SEVERE_CYCLONIC_STORM = "Severe Cyclonic Storm"
    VERY_SEVERE_CYCLONIC_STORM = "Very Severe Cyclonic Storm"
    EXTREMELY_SEVERE_CYCLONIC_STORM = "Extremely Severe Cyclonic Storm"
    SUPER_CYCLONIC_STORM = "Super Cyclonic Storm"
    WELL_MARKED_LOW = "Well Marked Low"


class TrackPoint(BaseModel):
    """Individual observation or forecast point along the cyclone trajectory."""

    timestamp: str = Field(description="ISO-8601 UTC timestamp")
    latitude: float = Field(ge=-90.0, le=90.0)
    longitude: float = Field(ge=-180.0, le=180.0)
    wind_speed_knots: float = Field(ge=0)
    wind_speed_kmph: Optional[float] = Field(default=None, ge=0)
    gust_speed_kmph: Optional[float] = Field(default=None, ge=0)
    central_pressure_hpa: float = Field(ge=800, le=1050)
    category: TrackCategory
    is_forecast: bool = Field(default=False)
    forecast_lead_hours: Optional[int] = Field(default=0, ge=0)
    cone_radius_km: Optional[float] = Field(default=0.0, ge=0)
    heading_degrees: Optional[float] = Field(default=None, ge=0, le=360)
    forward_speed_kmph: Optional[float] = Field(default=None, ge=0)


class CycloneTrack(BaseModel):
    """Complete cyclone track dataset containing metadata and ordered track points."""

    id: str = Field(description="Unique storm identifier (e.g. BOB-02-2019)")
    name: str = Field(description="Storm name designated by RSMC New Delhi")
    season_year: int = Field(ge=1900, le=2100)
    basin: str = Field(default="Bay of Bengal")
    current_status: str
    genesis_time: str
    dissipation_time: Optional[str] = None
    track_points: List[TrackPoint]


class VulnerabilityProperties(BaseModel):
    """Properties describing socio-economic, elevation, and shelter vulnerability for a district."""

    district_id: str
    district_name: str
    state_name: str
    total_population: int = Field(ge=0)
    vulnerable_population: int = Field(ge=0)
    coastal_length_km: float = Field(ge=0)
    average_elevation_m: float
    cyclone_risk_score: float = Field(ge=0.0, le=1.0)
    storm_surge_risk_m: float = Field(ge=0.0)
    shelter_capacity: int = Field(ge=0)
    shelter_count: int = Field(ge=0)
    hospital_count: int = Field(ge=0)
    primary_language: str
    secondary_language: Optional[str] = None


# Alias for backward and TypeScript naming compatibility
DistrictProperties = VulnerabilityProperties


class VulnerabilityGeometry(BaseModel):
    """GeoJSON geometry (Polygon or MultiPolygon)."""

    type: str = Field(pattern="^(Polygon|MultiPolygon)$")
    coordinates: list


class VulnerabilityFeature(BaseModel):
    """GeoJSON Feature representing a district vulnerability entity."""

    type: str = Field(default="Feature")
    properties: VulnerabilityProperties
    geometry: VulnerabilityGeometry


class VulnerabilityFeatureCollection(BaseModel):
    """GeoJSON FeatureCollection wrapper for district vulnerability layers."""

    type: str = Field(default="FeatureCollection")
    name: Optional[str] = None
    crs: Optional[dict] = None
    features: List[VulnerabilityFeature]


class MultilingualAdvisories(BaseModel):
    """Multilingual text advisories in target regional languages."""

    odia: str
    bengali: str
    telugu: str
    tamil: str
    hindi: str
    english: str


class ActionCategory(str, Enum):
    """Category of anticipatory action."""

    EVACUATION = "EVACUATION"
    SHELTER = "SHELTER"
    FISHERFOLK = "FISHERFOLK"
    AGRICULTURE = "AGRICULTURE"
    POWER_UTILITY = "POWER_UTILITY"
    HEALTHCARE = "HEALTHCARE"


class ActionUrgency(str, Enum):
    """Urgency level for anticipatory actions."""

    IMMEDIATE = "IMMEDIATE"
    WITHIN_12_HOURS = "WITHIN_12_HOURS"
    WITHIN_24_HOURS = "WITHIN_24_HOURS"
    PRECAUTIONARY = "PRECAUTIONARY"


class ActionItem(BaseModel):
    """Targeted actionable early warning instruction."""

    category: ActionCategory
    action: str
    urgency: ActionUrgency
    target_audience: str


class AdvisorySeverity(str, Enum):
    """Anticipatory advisory alert level."""

    WATCH = "WATCH"
    ALERT = "ALERT"
    WARNING = "WARNING"
    EMERGENCY_ACTION = "EMERGENCY_ACTION"


class AnticipatoryAdvisory(BaseModel):
    """Anticipatory action advisory payload generated by Gemini multimodal analysis."""

    advisory_id: str
    cyclone_id: str
    issued_at: str
    severity_level: AdvisorySeverity
    lead_time_hours: Optional[float] = Field(default=None, ge=0)
    estimated_landfall_time: Optional[str] = None
    estimated_landfall_location: Optional[str] = None
    max_expected_wind_kmph: Optional[float] = None
    max_expected_surge_m: Optional[float] = None
    target_districts: List[str]
    headline: str
    multilingual_advisories: MultilingualAdvisories
    recommended_actions: List[ActionItem]
    model: str = Field(default="gemini-3.7-flash", description="Model used to generate advisory")
